base_url = "https://history-lessons.netlify.app"

title = "Μαθήματα Ιστορίας"
description = "Μια ιστοσελίδα αφιερωμένη στην αντικειμενική και ελεύθερη εκμάθηση της παγκόσμιας ιστορίας."

default_language = "el"
